services:
  backend:
    build:
      context: .  # Contexto actual, donde está el Dockerfile del backend
    volumes:
      - ./src:/app/src  # Monta solo la carpeta src para desarrollo
    ports:
      - "3000:3000"  # Puerto del backend
    env_file: 
      - .env  # Cargar variables desde el archivo .env
    command: ["node", "src/server.js"]  # Comando para iniciar el backend

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Puerto de PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a
      POSTGRES_DB: Capstone

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  postgres_data:
